# Generated by Django 3.1.5 on 2021-01-09 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='member',
            options={'ordering': ('first_name',)},
        ),
    ]
