# Generated by Django 3.1.5 on 2021-01-23 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0002_auto_20210110_0244'),
    ]

    operations = [
        migrations.AddField(
            model_name='interest',
            name='definition',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='resume_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
