# Generated by Django 3.1.5 on 2021-01-23 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0003_auto_20210124_0139'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interest',
            name='definition',
        ),
        migrations.RemoveField(
            model_name='member',
            name='resume_url',
        ),
    ]
