# Generated by Django 3.1.5 on 2021-01-23 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0004_auto_20210124_0250'),
    ]

    operations = [
        migrations.AddField(
            model_name='interest',
            name='defination',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='resume_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
