# Generated by Django 3.1.5 on 2021-01-23 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0005_auto_20210124_0252'),
    ]

    operations = [
        migrations.RenameField(
            model_name='interest',
            old_name='defination',
            new_name='definition',
        ),
    ]
