# Generated by Django 3.1.5 on 2021-02-12 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0006_auto_20210124_0255'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='instagram_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
