# Generated by Django 3.1.5 on 2021-02-12 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0007_member_instagram_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=56)),
                ('name', models.CharField(max_length=56)),
                ('content', models.TextField()),
                ('entire_team', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('receiver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='group.member')),
            ],
            options={
                'ordering': ('-timestamp',),
            },
        ),
    ]
