# Generated by Django 3.1.5 on 2021-02-12 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0008_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='receiver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='group.member'),
        ),
    ]
