# Generated by Django 3.1.5 on 2021-02-12 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0009_auto_20210212_1910'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='content',
            new_name='your_message',
        ),
    ]
