# Generated by Django 3.1.5 on 2021-01-23 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('group', '0003_auto_20210124_0139'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='group.member')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='group.interest')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
